import type { Database } from "./types";

export function cedarSeed(): Database {
  return {
    brand: {
      logoUrl: "/brand/cedar-mark.svg",
      logoAccepted: true,
      primary: "#0D2C54",
      secondary: "#E8B923",
      accent: "#F7F1DE",
      textOnPrimary: "#FFFFFF",
      fonts: { heading: "Georgia, serif", body: "system-ui, sans-serif" },
      palette: ["#0D2C54", "#E8B923", "#F7F1DE"],
      detectedNote:
        "Navy + gold, formal academic look. Confirmed as Cedar’s default design system.",
    },
    school: {
      name: "Cedar School & College",
      levels: "Primary → College",
      campuses: ["Clifton"],
      tagline: "Inspiring minds. Building character.",
      mission:
        "A professional, warm, youthful academic community from primary through college.",
      phone: "+92 21 3587 0000",
      website: "https://www.cedar.edu.pk",
      address: "Clifton Campus, Karachi",
      admissionsLine: "Admissions open for the new academic year.",
      socials: {
        instagram: "@cedarschool",
        facebook: "Cedar School & College",
      },
    },
    tone: {
      chips: ["Professional", "Warm", "Youthful", "Academic"],
      studentNamesDefaultOff: true,
      noSlang: true,
    },
    vocab: {
      campuses: ["Clifton"],
      eventTypes: [
        "Sports Day",
        "Annual Day",
        "Science Fair",
        "Independence Day",
        "Cultural Day",
        "Teachers' Day",
        "Field Trip",
        "Debate Competition",
        "Art Exhibition",
      ],
      extraSpellings: {
        cliffton: "Clifton",
        ceder: "Cedar",
        cedar: "Cedar",
        "spots day": "Sports Day",
        "sport day": "Sports Day",
        "teachers day": "Teachers' Day",
      },
    },
    captionLanguageDefault: "en",
    posterLanguageDefault: "en",
    whatsappBilingual: false,
    jobs: [],
    folders: [
      {
        id: "fld-sports",
        name: "Sports Day",
        kind: "event_type",
        eventType: "Sports Day",
      },
      {
        id: "fld-sports-2026-clifton",
        parentId: "fld-sports",
        name: "Sports Day 2026 – Clifton",
        kind: "event",
        campus: "Clifton",
        year: "2026",
        eventType: "Sports Day",
      },
      {
        id: "fld-admissions",
        name: "Admissions",
        kind: "event_type",
        eventType: "Admissions",
      },
    ],
    assets: [],
    calendar: [
      {
        id: "cal-admissions",
        name: "Admissions Open",
        type: "Admissions",
        date: "2026-09-02",
        campus: "Clifton",
        source: "manual",
        approved: true,
        folderId: "fld-admissions",
      },
      {
        id: "cal-sports",
        name: "Annual Sports Day",
        type: "Sports Day",
        date: "2026-09-15",
        campus: "Clifton",
        grades: "6-10",
        source: "manual",
        approved: true,
        folderId: "fld-sports-2026-clifton",
      },
      {
        id: "cal-midterms",
        name: "Midterm exams",
        type: "Exam schedule",
        date: "2026-09-16",
        endDate: "2026-09-20",
        campus: "Clifton",
        source: "manual",
        approved: true,
      },
      {
        id: "cal-teachers",
        name: "Teachers' Day",
        type: "Teachers' Day",
        date: "2026-10-05",
        campus: "Clifton",
        source: "manual",
        approved: true,
      },
    ],
    campaigns: [],
    packets: [],
    email: {
      enabled: true,
      provider: null,
      connected: false,
      fromName: "Alara for Cedar",
      headEmail: "head@cedar.edu.pk",
      approverEmail: "",
      notifyLive: true,
      notifyApproval: true,
      notifyFailed: true,
      notifyScheduledToday: false,
      fromEmail: "",
    },
    notifications: [],
    users: {
      creatorName: "Communications",
      approverName: "Head of School",
      instagramConnected: false,
      facebookConnected: false,
    },
  };
}
